## 필요한 라이브러리 임폴트

In [2]:
import pandas as pd
import numpy as np

## 데이터 불러오기

In [3]:
data = pd.read_csv('final_data.csv')
print(data)

        광역시도명  시군구명          날짜  시간대별 시간  강수 유형명   습도값  강수량 값   기온값  풍속값  \
0           0     4  2019-07-12       18       0  0.91    0.0  22.6  1.5
1           0     4  2019-07-19       21       0  0.63    0.0  28.6  2.1
2           0     4  2019-07-22       12       0  0.92    0.0  25.9  1.0
3           0     4  2019-07-22       15       0  0.96    0.0  24.4  0.1
4           0     4  2019-07-22       18       0  0.94    0.0  24.7  0.6
...       ...   ...         ...      ...     ...   ...    ...   ...  ...
129288      2    19  2020-07-31       19       1  0.98    1.0  24.4  0.8
129289      2    19  2020-07-31       20       0  0.98    0.0  24.4  1.1
129290      2    19  2020-07-31       21       0  0.97    0.0  24.8  1.5
129291      2    19  2020-07-31       22       0  0.95    0.0  25.2  1.9
129292      2    19  2020-07-31       23       0  0.96    1.0  25.3  1.4

        한식_배달건수  ...  찜탕_배달건수  도시락_배달건수  패스트푸드_배달건수  가장 많은 배달    년도  월   일  \
0             0  ...        0         0           0         8  2019  7  12
1             0  ...        0         0           0         4  2019  7  19
2             0  ...        0         0           0         5  2019  7  22
3             0  ...        0         0           1         9  2019  7  22
4             0  ...        0         0           0         8  2019  7  22
...         ...  ...      ...       ...         ...       ...   ... ..  ..
129288       36  ...        5         0           6        11  2020  7  31
129289       36  ...        9         0           6        11  2020  7  31
129290       36  ...        1         0           3        11  2020  7  31
129291       18  ...        0         0           0        11  2020  7  31
129292       10  ...        0         0           0        11  2020  7  31

        요일  계절      불쾌지수
0        4   1  71.95334
1        4   1  78.29482
2        0   1  77.71272
3        0   1  75.52576
4        0   1  75.85082
...     ..  ..       ...
129288   4   1  75.72288
129289   4   1  75.72288
129290   4   1  76.33244
129291   4   1  76.82760
129292   4   1  77.11012

[129293 rows x 29 columns]

## 상관분석

In [ ]:
'''
1. 전체 컬럼 상관분석
2. 지역별 날씨 컬럼과 가장 많은 배달의 상관분석
3. 강수 유형별 날씨 컬럼과 가장 많은 배달의 상관분석
* 기본적으로 년도 나누어서 하기
'''

### 1. 서울, 경기, 인천 통합

### 1). 컬럼 별 상관분석

In [23]:
a = ['광역시도명','시군구명','시간대별 시간','강수 유형명','습도값','강수량 값','기온값','풍속값','년도','월','일','요일','계절', '불쾌지수', '가장 많은 배달']
total_1 = data[a]

## 상관분석
x = total_1.corr()
# print(x)

## 각 컬럼별 0.5 이상 혹은 -0.5 이하인 것 추출
for i in a:
    r = x[i]
    r = r.drop(index = i)
    t = r[r>=0.5]
    print(f'{i} 컬럼 상관분석 0.5 이상')
    print(t)
    print('-'*80)

## 결과
'''
1. 강수 유형과 강수량값은 서로 상관 관계 있음
2. 기온값과 불쾌지수는 아주 강한 상관 관계 있음
3. 모델링 하는데 더욱 필요로 하는 강수 유형과 기온값을 채택 
'''

광역시도명 컬럼 상관분석 0.5 이상
Series([], Name: 광역시도명, dtype: float64)
--------------------------------------------------------------------------------
시군구명 컬럼 상관분석 0.5 이상
Series([], Name: 시군구명, dtype: float64)
--------------------------------------------------------------------------------
시간대별 시간 컬럼 상관분석 0.5 이상
Series([], Name: 시간대별 시간, dtype: float64)
--------------------------------------------------------------------------------
강수 유형명 컬럼 상관분석 0.5 이상
강수량 값    0.512412
Name: 강수 유형명, dtype: float64
--------------------------------------------------------------------------------
습도값 컬럼 상관분석 0.5 이상
Series([], Name: 습도값, dtype: float64)
--------------------------------------------------------------------------------
강수량 값 컬럼 상관분석 0.5 이상
강수 유형명    0.512412
Name: 강수량 값, dtype: float64
--------------------------------------------------------------------------------
기온값 컬럼 상관분석 0.5 이상
불쾌지수    0.992963
Name: 기온값, dtype: float64
--------------------------------------------------------------------------------
풍속값 컬럼 상관분석 0.5 이상
Series([], Name: 풍속값, dtype: float64)
--------------------------------------------------------------------------------
년도 컬럼 상관분석 0.5 이상
Series([], Name: 년도, dtype: float64)
--------------------------------------------------------------------------------
월 컬럼 상관분석 0.5 이상
Series([], Name: 월, dtype: float64)
--------------------------------------------------------------------------------
일 컬럼 상관분석 0.5 이상
Series([], Name: 일, dtype: float64)
--------------------------------------------------------------------------------
요일 컬럼 상관분석 0.5 이상
Series([], Name: 요일, dtype: float64)
--------------------------------------------------------------------------------
계절 컬럼 상관분석 0.5 이상
Series([], Name: 계절, dtype: float64)
--------------------------------------------------------------------------------
불쾌지수 컬럼 상관분석 0.5 이상
기온값    0.992963
Name: 불쾌지수, dtype: float64
--------------------------------------------------------------------------------
가장 많은 배달 컬럼 상관분석 0.5 이상
Series([], Name: 가장 많은 배달, dtype: float64)
--------------------------------------------------------------------------------

### 2). 최종 모델링에 사용 되었던 컬럼 별 상관분석

In [24]:
a = ['시군구명','시간대별 시간','강수 유형명','습도값','기온값','풍속값','년도','월','일','요일','계절','가장 많은 배달']
total_2 = data[a]

## 상관분석 
x = total_2.corr()

## 각 컬럼별 0.5 이상 혹은 -0.5 이하인 것 추출
for i in a:
    r = x[i]
    r = r.drop(index = i)
    t = r[r>=0.5]
    print(f'{i} 컬럼 상관분석 0.5 이상')
    print(t)
    print('-'*80)
    
## 결과 
'''
1. 각 컬럼별 상관 관계가 있는 것이 없음 모든 컬럼 사용 
'''

시군구명 컬럼 상관분석 0.5 이상
Series([], Name: 시군구명, dtype: float64)
--------------------------------------------------------------------------------
시간대별 시간 컬럼 상관분석 0.5 이상
Series([], Name: 시간대별 시간, dtype: float64)
--------------------------------------------------------------------------------
강수 유형명 컬럼 상관분석 0.5 이상
Series([], Name: 강수 유형명, dtype: float64)
--------------------------------------------------------------------------------
습도값 컬럼 상관분석 0.5 이상
Series([], Name: 습도값, dtype: float64)
--------------------------------------------------------------------------------
기온값 컬럼 상관분석 0.5 이상
Series([], Name: 기온값, dtype: float64)
--------------------------------------------------------------------------------
풍속값 컬럼 상관분석 0.5 이상
Series([], Name: 풍속값, dtype: float64)
--------------------------------------------------------------------------------
년도 컬럼 상관분석 0.5 이상
Series([], Name: 년도, dtype: float64)
--------------------------------------------------------------------------------
월 컬럼 상관분석 0.5 이상
Series([], Name: 월, dtype: float64)
--------------------------------------------------------------------------------
일 컬럼 상관분석 0.5 이상
Series([], Name: 일, dtype: float64)
--------------------------------------------------------------------------------
요일 컬럼 상관분석 0.5 이상
Series([], Name: 요일, dtype: float64)
--------------------------------------------------------------------------------
계절 컬럼 상관분석 0.5 이상
Series([], Name: 계절, dtype: float64)
--------------------------------------------------------------------------------
가장 많은 배달 컬럼 상관분석 0.5 이상
Series([], Name: 가장 많은 배달, dtype: float64)
--------------------------------------------------------------------------------

'\n\n'